Algoritmo "entradaDeDados"

Var
   idade : inteiro
   salario1, salario2 : real
   nome : caractere


Inicio
  escreval("Digite sua idade: ")
  leia(idade)
  escreval("Digite os 2 ultimos salarios...")
  leia(salario1)
  leia(salario2)
  escreval("Digite sua nome: ")
  leia(nome)
  
  escreval("Dados digitados:")
  escreval("Sua idade é = ", idade)
  escreval("Os dois ultimos salarios foi = ", salario1, salario2)
  escreval("Sua nome é = ", nome)
  
Fimalgoritmo