Algoritmo "aula25"



Var
  a, b, c, d, x, y, z : real


Inicio

  x <- 2.0
  y <- 3.0
  z <- 7.0
  
  a <- Exp(x, y)//faz o valor x elevado a y
  b <- RaizQ(y)//Vamos obter a raiz quadrada de um valor
  c <- Pi //Variavel recebe o valor de PI
  d <- abs(x)//Recebe o valor absoluto de um valor quebrado

  escreval(a)
  escreval(b)
  escreval(c)
  escreval(d)



Fimalgoritmo