Algoritmo "enquanto"




Var

    n1, n2 : inteiro


Inicio

      n1 <- 0
      n2 <- 1

      enquanto n1 <> n2 faca
      escreval("Digite dois numeros: ")
      leia(n1)
      leia(n2)

      se n1 > n2 entao
         escreval("DESCRESCENTE!")
      senao
            se n2 > n1 entao
               escreval("CRESCENTE!")
           fimse
      fimse

      fimenquanto


Fimalgoritmo